CREATE EXTENSION IF NOT EXIST "uuid-ossp";
CREATE EXTENSION IF NOT EXIST "pgcrypto";
CREATE EXTENSION IF NOT EXIST "pg_stat_statements";

CREATE EXTENSION IF NOT EXIST timescaledb CASCADE;

CREATE EXTENSION IF NOT EXIST pg_partman;

CREATE EXTENSION IF NOT EXIST pg_cron;

CREATE EXTENSION IF NOT EXIST vector;